<?php

/**
 * Implements hook_form_alter().
 */
function webspark_utility_form_media_library_add_form_upload_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  $form['#attached']['library'][] = 'webspark_utility/medialibrary';
}

/**
 * Implements hook_entity_bundle_field_info_alter().
 */
function webspark_utility_entity_bundle_field_info_alter(&$fields, \Drupal\Core\Entity\EntityTypeInterface $entity_type, $bundle) {
  if ($bundle === 'hero') {
    if (isset($fields['field_hero_unformatted_text'])) {
      // Use the ID as defined in the annotation of the constraint definition
      $fields['field_hero_unformatted_text']->addConstraint('HeroCharacterConstraint', []);
    }
  }
}

/**
 * Implements hook_field_widget_WIDGET_TYPE_form_alter()
 */
function webspark_utility_field_widget_field_menu_tree_widget_form_alter(&$element, \Drupal\Core\Form\FormStateInterface $form_state, $context) {
  // Remove the default menus. If you need more in depth solution, check the
  // locked parameter; parentSelectElement() method doesnt have an option for this.
  $default_menus = ['account', 'admin', 'devel', 'footer', 'main', 'tools'];
  foreach ($element['menu_item_key']['#options'] as $key => $menu) {
    $menu_key = substr($key, 0, strpos($key, ":"));
    if (in_array($menu_key, $default_menus)) {
      unset($element['menu_item_key']['#options'][$key]);
    }
  }

}
